[project]
name = "hello"
version = "0.1.2.3"
description = "Sample cx_Freeze script"

[tool.cxfreeze]
executables = [
    "hello.py",
    {script = "hello.py", target_name = "hello2"}
]

[tool.cxfreeze.build_exe]
excludes = ["tkinter", "unittest"]
