version: 2
updates:
  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    directory: "/"
    groups:
      monthly-batch:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    cooldown:
      default-days: 7
    directory: "/"
    groups:
      monthly-batch:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pre-commit"
    cooldown:
      default-days: 7
    directory: "/"
    groups:
      monthly-batch:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
