ci:
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate [ci skip]"
  skip: [blacken-docs, build-docs, shellcheck]

default_language_version:
  python: python3.12

exclude: |
  (?x)^(
      cx_Freeze/hooks/_pyqt5_/_resource.py|
      cx_Freeze/hooks/_pyside2_/_resource.py|
      cx_Freeze/hooks/_pyside6_/_resource.py|
      cx_Freeze/importshed/.*.pyi|
      doc/src/conf.py
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: 4b2e70d08cb2ccd26d1fba73588de41c7a5d50b7 # frozen: v0.25
    hooks:
      - id: validate-pyproject
        additional_dependencies:
          - validate-pyproject-schema-store[all]>=2025.11.14

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: b831c3dc5d27d9da294ae4e915773b99aa24a7c5 # frozen: v0.15.10
    hooks:
      - id: ruff-check
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

  - repo: https://github.com/adamchainz/blacken-docs
    rev: fda77690955e9b63c6687d8806bafd56a526e45f # frozen: 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==26.3.1
        args: ["-l", "79"]

  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a # frozen: v2.4.2
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args: ["--ignore-words-list=lief,LIEF", "-w", "--skip=*.rtf"]
        exclude: (?x)^(cx_Freeze/hooks/global_names.py)$

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: b25652612a4a3c1da8caccfca9af661db56b2c07 # frozen: v3.8.2
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95 # frozen: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: build-docs
        name: build sphinx docs
        language: unsupported
        entry: make -C doc html
        always_run: true
        pass_filenames: false

  - repo: local
    hooks:
      - id: requirements
        name: requirements
        language: unsupported
        entry: python ci/requirements.py
        files: ^(pyproject.toml|requirements.txt|requirements-dev.txt|
          doc/requirements.txt|tests/requirements.txt
          )$
