version: 2

sphinx:
  builder: html
  configuration: doc/src/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
