version: 2

sphinx:
  builder: html
  configuration: doc/src/conf.py
  fail_on_warning: true

formats: all

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
