version: 2

sphinx:
  builder: html
  configuration: doc/src/conf.py
  fail_on_warning: true

formats: all

python:
  version: 3.9
  install:
    - method: pip
      path: .
    - requirements: doc/requirements.txt
