# Generated by cx_Freeze

import collections, re
import PyQt6.sip
from PyQt6 import QtCore
from PyQt6 import QtGui
from PyQt6 import QtNetwork
from PyQt6 import QtMultimedia
from PyQt6 import QtWidgets
import datetime
from warnings import deprecated
