# Generated by cx_Freeze

import collections, enum, re
import PyQt6.sip
from PyQt6 import QtCore
from PyQt6 import QtNetwork
from PyQt6 import QtQml
from PyQt6 import QtGui
from PyQt6 import QtWebChannel
from PyQt6 import QtWebEngineCore
import datetime
from warnings import deprecated
