name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build_wheel:
    name: Build wheels
    uses: ./.github/workflows/build-wheel.yml

  testpypi:
    name: Publish package to TestPyPI
    needs:
      - build_wheel
    if: |
      github.event_name != 'workflow_dispatch' &&
      !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    environment:
      name: ${{ github.event_name }}
      url: https://test.pypi.org/p/cx-Freeze
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Download all artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: wheelhouse
          pattern: cx-freeze-wheel
          merge-multiple: true

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          packages-dir: wheelhouse/
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true

  tests:
    needs: build_wheel
    runs-on: ${{ matrix.os }}-${{ matrix.os_version }}
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        os_version: [latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]
    defaults:
      run:
        shell: bash
    env:
      UV_NO_PROGRESS: true
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -qy alien fakeroot rpm

      - name: Fetch only the required files for testing
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            ci
            pyproject.toml
            samples
            tests

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          activate-environment: true
          cache-dependency-glob: "pyproject.toml"
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Download the wheel
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          merge-multiple: true
          pattern: cx-freeze-wheel
          path: wheelhouse

      - name: Install dependencies to test
        run: ci/install-tools.sh --tests

      - name: Install cx_Freeze from wheelhouse
        run: |
          uv pip install cx_Freeze -f wheelhouse \
              --no-build --no-deps --no-index --prerelease=allow --reinstall

      - name: Generate coverage report
        run: uv run --no-project coverage run

      - name: Upload coverage reports
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: cov-${{ matrix.python-version }}.${{ matrix.os }}-${{ strategy.job-index }}
          path: .coverage.*
          include-hidden-files: true

  coverage:
    needs:
      - tests
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true

      - name: Download coverage data
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: cov-*
          merge-multiple: true

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@7188638f871f721a365d644f505d1ff3df20d683 # v3.40
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MERGE_COVERAGE_FILES: true

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
