name: Publish packages

on:
  workflow_run:
    workflows: ["Build wheel"]
    types:
      - completed

jobs:
  testpypi:
    name: Publish package to TestPyPI
    if: |
      (github.event.workflow_run.event == 'pull_request' ||
      github.event.workflow_run.event == 'push' ||
      github.event.workflow_run.event == 'workflow_dispatch')
      && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name }}
      url: https://test.pypi.org/p/cx-Freeze
    permissions:
      actions: read
      id-token: write
    steps:

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: wheelhouse
          pattern: cx-freeze-whl-*
          merge-multiple: true

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse/
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true
